substitutions:
  uart_dummy_tx: GPIO9
  uart_tx: GPIO4
  uart_rx: GPIO5
  modbus_id: modbus1

esphome:
  name: wv8840c
  friendly_name: WV8840C Water Heater Control

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

packages:
  remote_package:
    url: https://github.com/russdill/resideo
    ref: main
    refresh: 5min
    files:
      - packages/modbus-esp32c3.yaml
      - packages/wv8840c-modbus.yaml
